baseURL = "https://akrisanov.com/"
languageCode = "ru-ru"
title = "ĞĞ½Ğ´Ñ€ĞµĞ¹ ĞšÑ€Ğ¸ÑĞ°Ğ½Ğ¾Ğ²"
theme = "hyde-hyde"

[params]
  description = "Ğ—Ğ°Ğ¼ĞµÑ‚ĞºĞ¸ (Ğ½Ğµ) Ñ€Ğ°Ğ·Ñ€Ğ°Ğ±Ğ¾Ñ‚Ñ‡Ğ¸ĞºĞ°"
  copyright = "Andrey Krisanov"
  license = "MIT"
  relatedPosts = true
  highlightjs = true
  highlightjslanguages = ["shell", "python", "go"]

[Menus]
  main = [
      {Name = "â–¶ Ğ—Ğ°Ğ¼ĞµÑ‚ĞºĞ¸", URL = "/posts/"},
      {Name = "ğŸ™ Github", URL = "https://github.com/akrisanov/"},
      {Name = "ğŸ‘¨ğŸ¼â€ğŸ’» LinkedIn", URL = "https://www.linkedin.com/in/akrisanov/"},
      {Name = "ğŸ©³ Telegram-ĞºĞ°Ğ½Ğ°Ğ»", URL = "https://t.me/techleadnotes"}
  ]
